version: "2.2"

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    # ports:
    #   - "27017:27017"

  api:
    image: instaapi:2.0.0
    environment:
      - DATABASE_HOST=mongo
      # - DATABASE_PORT=27017
    volumes:
      - uploads:/usr/src/app/uploads
    # A API tem que ser exposta em um endereço válido na rede,
    # pois o client web é Single Application
    ports:
      - "8180:8080"
    # Constroi a imagem da API
    build:
      context: ./api

  client:
    image: instacli:2.0.0
    labels:
      - "com.service.context=/client"
    environment:
      - API_ADDRESS=192.168.99.100
      - API_PORT=8180
    ports:
      - "8080:8080"
    # Constroi a imagem do Client
    build:
      context: ./cliente_web
    # scale: 2

volumes:
  mongo:
    driver: local

  uploads:
    driver: local
