version: "2.2"

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    # ports:
    #   - "27017:27017"

  api:
    image: instaapi:latest
    environment:
      - DATABASE_HOST=mongo
      # - DATABASE_PORT=27017
    volumes:
      - uploads:/usr/src/app/uploads
    # A API tem que ser exposta em um endereço válido na rede,
    # pois o client web é Single Application
    ports:
      - "8180:8080"

  client:
    image: instacli:latest
    environment:
      >> ver pq o endereço correto da api não é pego pelo container
      - API_ADDRESS=192.168.0.11
      - API_ADDRESS=8180
    ports:
      - "9000:8080"
    # scale: 2

volumes:
  mongo:
    driver: local

  uploads:
    driver: local
