version: "2"

services:
  mongo:
    image: mongo:latest
    # environment:
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
      - "28017:28017"

volumes:
  mongo:
    driver: local
